#ifndef CONTROLLER_TOUCHSCREEN_TEXTURES_H
#define CONTROLLER_TOUCHSCREEN_TEXTURES_H
#ifdef TOUCH_CONTROLS
#include "macros.h"
#include "types.h"

enum TouchTextureIndex {
    TEXTURE_TOUCH_BUTTON,
    TEXTURE_TOUCH_BUTTON_DARK,
    TEXTURE_TOUCH_CUP,
    TEXTURE_TOUCH_CDOWN,
    TEXTURE_TOUCH_CLEFT,
    TEXTURE_TOUCH_CRIGHT,
    TEXTURE_TOUCH_UP,
    TEXTURE_TOUCH_DOWN,
    TEXTURE_TOUCH_LEFT,
    TEXTURE_TOUCH_RIGHT,
    TEXTURE_TOUCH_CHECK,
    TEXTURE_TOUCH_CROSS,
    TEXTURE_TOUCH_RESET,
    TEXTURE_TOUCH_SNAP,
    TEXTURE_TOUCH_TRASH,
    TOUCH_TEXTURE_COUNT,
}; 

extern const u8 *const touch_textures[TOUCH_TEXTURE_COUNT];

#endif
#endif